version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - run: export USERNAME=$JQUANTS_USER && export PASSWORD=$JQUANTS_PWD && go test -v